module.exports = {
  apps: [
    {
      name: 'monitoring-worker',
      script: '/tmp/cc-agent/61105712/project/backend/start-monitoring.sh',
      cwd: '/tmp/cc-agent/61105712/project/backend',
      interpreter: '/bin/bash',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/tmp/cc-agent/61105712/project/backend/logs/monitoring-error.log',
      out_file: '/tmp/cc-agent/61105712/project/backend/logs/monitoring-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'dispatcher-worker',
      script: '/tmp/cc-agent/61105712/project/backend/start-dispatcher.sh',
      cwd: '/tmp/cc-agent/61105712/project/backend',
      interpreter: '/bin/bash',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/tmp/cc-agent/61105712/project/backend/logs/dispatcher-error.log',
      out_file: '/tmp/cc-agent/61105712/project/backend/logs/dispatcher-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
